---
apiVersion: v2
description: A chart to power Plexio (plexio.stream) running on kubernetes
name: plexio
version: 0.2.0-rc2
appVersion: 0.0.2rc1
home: https://plexio.stream/
icon: https://raw.githubusercontent.com/vanchaxy/plexio/main/webapp/public/logo512.png
sources:
  - https://github.com/vanchaxy/plexio/tree/main/charts/plexio
  - https://github.com/vanchaxy/plexio
maintainers:
  - name: vanchaxy
    email: plexio@ivanchenko.io
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.3.0
  - name: redis
    condition: redis.enabled
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 18.5.0
