---
{{- include "bjw-s.common.loader.init" . }}

{{- define "immich.plex-matcher.hardcodedValues" -}}
global:
  nameOverride: plex-matcher

service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        primary: true
        port: 32400
        protocol: HTTP

controllers:
  main:
    containers:
      main:
        probes:
          liveness: &probes
            enabled: false
          readiness: *probes
          startup: *probes
    initContainers:
      init-dummy:
        image:
          repository: docker.io
          tag: busybox:1.36
          pullPolicy: IfNotPresent
        command:
          - 'wget'
          - 'https://github.com/vanchaxy/plexio/raw/main/dummy.mp4'
          - '-O'
          - '/dummy/3u53SlRs3c - 1x1 - 3u53SlRs3c - 1080p.mp4'

persistence:
  config:
    enabled: true
    advancedMounts:
      main:
        main:
          - path: /config
  dummy:
    enabled: true
    type: emptyDir
    advancedMounts:
      main:
        main:
          - path: /dummy
        init-dummy:
          - path: /dummy
{{- end }}


{{ if (index .Values "plex-matcher").enabled }}
{{- $ctx := deepCopy . -}}
{{- $_ := mergeOverwrite $ctx.Values (index .Values "plex-matcher") -}}
{{- $_ = mergeOverwrite $ctx.Values (include "immich.plex-matcher.hardcodedValues" . | fromYaml) -}}
{{- include "bjw-s.common.loader.generate" $ctx }}
{{ end }}
