---
{{- include "bjw-s.common.loader.init" . }}

{{- define "immich.server.hardcodedValues" -}}
global:
  nameOverride: server

service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        primary: true
        port: 7777
        protocol: HTTP

controllers:
  main:
    containers:
      main:
        probes:
          liveness: &probes
            enabled: false
          readiness: *probes
          startup: *probes

{{- end }}


{{ if (index .Values "server").enabled }}
{{- $ctx := deepCopy . -}}
{{- $_ := mergeOverwrite $ctx.Values (index .Values "server") -}}
{{- $_ = mergeOverwrite $ctx.Values (include "immich.server.hardcodedValues" . | fromYaml) -}}
{{- include "bjw-s.common.loader.generate" $ctx }}
{{ end }}
